# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

# Pretty prompt. In color, displays 'username@hostname:pwd] $ '.
PS1='[\[\033[36m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]] $ '

# Source the bash aliases. Only contains aliases.
. /home/danijohn/.bash_aliases

# Setup Base16 so it is easy to change themes from any terminal.
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# Makes bash-completion package way sexier.
. /usr/share/bash-completion/bash_completion

# Help gnome terminal open new tabs in the same directory.
. /etc/profile.d/vte.sh

# Add home bin to path.
export PATH=$PATH:/home/danijohn/bin

# Attempting to tell everyone to use vim as the default editor.
export VISUAL=vim
export EDITOR="$VISUAL"
