# Sudo trick so aliases are evaluated on the command being passed to sudo.
# If an alias ends in whitespace or tab, then the next command is also
# evaluted to see if it is an alias.
alias sudo='sudo '

# vi aliases.
alias vi=vim

# ls aliases.
alias ls='ls --color=auto'
alias ll='ls -la --color=auto'
alias l='ls -1 --color=auto'

# Python.
alias p3='python3'

# Make pacman pretty
alias pacman='pacman --color=always '
