" DJ: Going to leave this off for a bit. Doesn't seem to add anything.
"runtime! archlinux.vim " Source the arch linux vim configuration first

set relativenumber  " Use relative numbers to make motions more useful

set title           " Show the title of the file in the title of the terminal

set tabstop=3       " Number of spaces that a <Tab> in the file counts for.

set shiftwidth=3    " Number of spaces to indent when using '<' or '>'

set expandtab       " Tabs will be automatically converted to spaces.

set showcmd         " Show (partial) command in status line.

set number          " Show line numbers.

set showmatch       " When a bracket is inserted, briefly jump to the matching
                    " one. The jump is only done if the match can be seen on the
                    " screen. The time to show the match can be set with
                    " 'matchtime'.

set hlsearch        " When there is a previous search pattern, highlight all
                    " its matches.

set incsearch       " While typing a search command, show immediately where the
                    " so far typed pattern matches.

set ignorecase      " Ignore case in search patterns.

set smartcase       " Override the 'ignorecase' option if the search pattern
                    " contains upper case characters.

set autoindent      " Copy indent from current line when starting a new line
                    " (typing <CR> in Insert mode or when using the "o" or "O"
                    " command).

set ruler           " Show the line and column number of the cursor position,
                    " separated by a comma.

" DJJ: Going to leave this off for a bit. Breaks some syntax highlighting.
"set background=dark " When set to "dark", Vim will try to use colors that look
"                    " good on a dark background. When set to "light", Vim will
"                    " try to use colors that look good on a light background.
"                    " Any other value is illegal.
"
set mouse=          " Disable the use of the mouse.

 syntax on           " Turn on syntax highlighting.

autocmd FileType make setlocal noexpandtab " Makefiles are special flowers and
                                           " need tabs to behave correctly.

autocmd FileType python setlocal tabstop=4   " Sel coding standard says 4 spaces
autocmd FileType python setlocal shiftwidth=4

autocmd FileType cucumber setlocal tabstop=4 " for python. Expanding this to
                                             " feature files as well
autocmd FileType cucumber setlocal shiftwidth=4

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

" Base16 vim colorscheme
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif

" Always turn on the spell checker.
set spell

" Make the spell check work with base16. The default highlighting doesn't work
" so I went with underlines.
hi clear SpellBad
hi SpellBad    cterm=underline
" I don't care about capitalization darn it!
set spellcapcheck=

" disables opaque background for use with Base16
hi Normal ctermbg=none
hi NonText ctermbg=none
