runtime! archlinux.vim " Source the arch linux vim configuration first

set title           " Show the title of the file in the title of the terminal

set tabstop=3       " Number of spaces that a <Tab> in the file counts for.

set expandtab       " Tabs will be automatically converted to spaces.

set showcmd         " Show (partial) command in status line.

set number          " Show line numbers.

set showmatch       " When a bracket is inserted, briefly jump to the matching
                    " one. The jump is only done if the match can be seen on the
                    " screen. The time to show the match can be set with
                    " 'matchtime'.

set hlsearch        " When there is a previous search pattern, highlight all
                    " its matches.

set incsearch       " While typing a search command, show immediately where the
                    " so far typed pattern matches.

set ignorecase      " Ignore case in search patterns.

set smartcase       " Override the 'ignorecase' option if the search pattern
                    " contains upper case characters.

set autoindent      " Copy indent from current line when starting a new line
                    " (typing <CR> in Insert mode or when using the "o" or "O"
                    " command).

set ruler           " Show the line and column number of the cursor position,
                    " separated by a comma.

set background=dark " When set to "dark", Vim will try to use colors that look
                    " good on a dark background. When set to "light", Vim will
                    " try to use colors that look good on a light background.
                    " Any other value is illegal.

set mouse=          " Enable the use of the mouse.

syntax on           " Turn on syntax highlighting.

autocmd FileType make setlocal noexpandtab " Makefiles are special flowers and
                                           " need tabs to behave correctly.

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

" Base16 vim colorscheme
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif
" disables opaque background for use with Base16
hi Normal ctermbg=none
hi NonText ctermbg=none

" Make trailing whitespace noticeable
highlight BadWhite ctermbg=red guibg=red
match BadWhite  /\s\+$/
"match BadWhite  /\t\+/
